version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 952662370353.dkr.ecr.us-east-1.amazonaws.com/uda-analytics
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...
      - docker build -t uda-analytics:latest -f ./analytics/Dockerfile
      - docker tag $IMAGE_REPO_NAME:latest 952662370353.dkr.ecr.us-east-1.amazonaws.com/uda-analytics:latest
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push 952662370353.dkr.ecr.us-east-1.amazonaws.com/uda-analytics:latest